In [1]:
import Classifier
import numpy as np

In [2]:
NB = Classifier.NaiveBayes()

In [18]:
examples = np.array([[1, 2, 2, 3], [5,6,7,8]])
label = np.array([0, 1])
NB.train(examples = examples, label = label)

NameError: name 'example' is not defined

In [6]:
import numpy as np
import pandas as pd
c = np.array([[1],[ 2]])
b = np.array([[1, 2, 2, 3], [5,6,7,8]])
print(np.divide(b, c))
for c, value in enumerate(b):
    print(c, value)

[[1.  2.  2.  3. ]
 [2.5 3.  3.5 4. ]]
0 [1 2 2 3]
1 [5 6 7 8]


In [12]:
c = np.array([1, 2, 2])
a = pd.Series(c)
k = a.value_counts(sort=False)
k.values

array([1, 2], dtype=int64)

In [46]:
c = a.value_counts(sort=False)
print("shape:", c.shape[0])
print(c)
print(c.sum())
print(c.index[0])

shape: 3
1    1
2    2
3    1
dtype: int64
4
1


In [40]:
c = np.zeros(b.shape)
c = np.divide(b[b>2], 3)
c

array([1.])

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
##        label_seires = pd.Series(label)
##        class_count = label_seires.value_counts(sort=False)
##        num_of_class = class_count.shape[0]
##        total_feature_count = np.zeros(num_of_class)
##        self.prior_prob = np.zeros(num_of_class)
##        all_count = class_count.sum()
##        num_of_feature = examples.shape[1]
##        print( examples.shape[1])
##        self.conditional = np.zeros((num_of_class, num_of_feature))
##        mask = label
##        for index in range(num_of_class):
##            prior_prob[index] = class_count[index] / all_count
##            mask[mask == class_count.index[index]] = class_count[index]
##        temp_condi = np.divide(example, mask)
##        for each_class in range(num_of_class):
##            for index, value in enumerate(temp_condi):
##                if(label[index] == class_count.index[each_class]):
##                    self.conditional[each_class, :] += value
##        print('conditional probability: ', self.conditional)
##        print('prior probability:', self.prior_prob)